[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/Mo2BW9yyOXwoakaFTNbCy", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/Aq47N7n_aUnyqWaENponB" }
remappings = [
    '@opnezeppelin/=lib/openzeppelin-contracts/',
    '@chainlink-ccip/=lib/ccip/',
    '@chainlink/local/=lib/chainlink-local/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
